/**
 * Sectional configuration diagram cards — AUTO-GENERATED by
 *   py -3 tools/sectional-diagrams/build_sectional_configs_from_registry.py
 * Source: sectional_styles_registry.json + Palliser PDFs + mccabe_plp_codes.json
 */
(function () {
  var _base =
    typeof window !== "undefined" && window.MTL_SECTIONAL_DIAGRAM_BASE
      ? String(window.MTL_SECTIONAL_DIAGRAM_BASE).trim()
      : "https://raw.githubusercontent.com/emcc10/mccabe-site/main/vspfiles/sectional-diagrams/";
  if (!_base) {
    _base = "https://raw.githubusercontent.com/emcc10/mccabe-site/main/vspfiles/sectional-diagrams/";
  }
  _base = _base.replace(/\/?$/, '/');

  function img(name) {
    return _base + name;
  }

  window.MTL_SECTIONAL_CONFIGS = {
    Alula: [
      {
        code: "07-15",
        label: "07-15",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Alula-SC-07-15.png"),
      },
      {
        code: "12-40",
        label: "12-40",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Alula-SC-12-40.png"),
      },
      {
        code: "07-09-08",
        label: "07-09-08",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Alula-SC-07-09-08.png"),
      },
      {
        code: "07-09-19",
        label: "07-09-19",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Alula-SC-07-09-19.png"),
      },
    ],
    Acacia: [
      {
        code: "67-10-09-10-66",
        label: "67-10-09-10-66",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Acacia-SC-67-10-09-10-66.png"),
      },
      {
        code: "67-10-09-60-66",
        label: "67-10-09-60-66",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Acacia-SC-67-10-09-60-66.png"),
      },
      {
        code: "67-W2-10-09-10-66",
        label: "67-W2-10-09-10-66",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Acacia-SC-67-W2-10-09-10-66.png"),
      },
      {
        code: "67-W2-10-09-60-66",
        label: "67-W2-10-09-60-66",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Acacia-SC-67-W2-10-09-60-66.png"),
      },
    ],
    Atticus: [
      {
        code: "07-15",
        label: "07-15",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Atticus-SC-07-15.png"),
      },
      {
        code: "07-40",
        label: "07-40",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Atticus-SC-07-40.png"),
      },
      {
        code: "07-11-08",
        label: "07-11-08",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Atticus-SC-07-11-08.png"),
      },
    ],
    Colebrook: [
      {
        code: "07-15",
        label: "07-15",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Colebrook-SC-07-15.png"),
      },
      {
        code: "07-35",
        label: "07-35",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Colebrook-SC-07-35.png"),
      },
      {
        code: "07-40",
        label: "07-40",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Colebrook-SC-07-40.png"),
      },
      {
        code: "12-40",
        label: "12-40",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Colebrook-SC-12-40.png"),
      },
    ],
    Creighton: [
      {
        code: "07-40",
        label: "07-40",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Creighton-SC-07-40.png"),
      },
      {
        code: "12-35",
        label: "12-35",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Creighton-SC-12-35.png"),
      },
      {
        code: "12-40",
        label: "12-40",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Creighton-SC-12-40.png"),
      },
      {
        code: "07-09-08",
        label: "07-09-08",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Creighton-SC-07-09-08.png"),
      },
    ],
    Lexi: [
      {
        code: "92-15",
        label: "92-15",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Lexi-SC-92-15.png"),
      },
      {
        code: "92-40",
        label: "92-40",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Lexi-SC-92-40.png"),
      },
      {
        code: "39-10-19",
        label: "39-10-19",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Lexi-SC-39-10-19.png"),
      },
    ],
    Barrett: [
      {
        code: "07-15",
        label: "07-15",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Barrett-SC-07-15.png"),
      },
      {
        code: "12-35",
        label: "12-35",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Barrett-SC-12-35.png"),
      },
      {
        code: "39-14-15",
        label: "39-14-15",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Barrett-SC-39-14-15.png"),
      },
    ],
    Corissa: [
      {
        code: "07-15",
        label: "07-15",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Corissa-SC-07-15.png"),
      },
      {
        code: "12-40",
        label: "12-40",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Corissa-SC-12-40.png"),
      },
      {
        code: "07-09-08",
        label: "07-09-08",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Corissa-SC-07-09-08.png"),
      },
      {
        code: "07-09-19",
        label: "07-09-19",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Corissa-SC-07-09-19.png"),
      },
    ],
    Juno: [
      {
        code: "07-15",
        label: "07-15",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Juno-SC-07-15.png"),
      },
      {
        code: "12-40",
        label: "12-40",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Juno-SC-12-40.png"),
      },
      {
        code: "07-09-08",
        label: "07-09-08",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Juno-SC-07-09-08.png"),
      },
      {
        code: "07-09-19",
        label: "07-09-19",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Juno-SC-07-09-19.png"),
      },
    ],
    Jura: [
      {
        code: "12-35",
        label: "12-35",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Jura-SC-12-35.png"),
      },
    ],
    Brookes: [
      {
        code: "92-15",
        label: "92-15",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Brookes-SC-92-15.png"),
      },
      {
        code: "92-40",
        label: "92-40",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Brookes-SC-92-40.png"),
      },
      {
        code: "39-10-19",
        label: "39-10-19",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Brookes-SC-39-10-19.png"),
      },
      {
        code: "92-11-93",
        label: "92-11-93",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Brookes-SC-92-11-93.png"),
      },
    ],
    Leeds: [
      {
        code: "07-40",
        label: "07-40",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Leeds-SC-07-40.png"),
      },
      {
        code: "12-35",
        label: "12-35",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Leeds-SC-12-35.png"),
      },
      {
        code: "12-40",
        label: "12-40",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Leeds-SC-12-40.png"),
      },
      {
        code: "07-09-08",
        label: "07-09-08",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Leeds-SC-07-09-08.png"),
      },
    ],
    Charli: [
      {
        code: "92-9W-93",
        label: "92-9W-93",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Charli-SC-92-9W-93.png"),
      },
      {
        code: "e3-90-e4",
        label: "e3-90-e4",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Charli-SC-e3-90-e4.png"),
      },
      {
        code: "E4-90-E3",
        label: "E4-90-E3",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Charli-SC-E4-90-E3.png"),
      },
      {
        code: "E4-90-11-90-E3",
        label: "E4-90-11-90-E3",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Charli-SC-E4-90-11-90-E3.png"),
      },
      {
        code: "E4-E2-9W-10-19",
        label: "E4-E2-9W-10-19",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Charli-SC-E4-E2-9W-10-19.png"),
      },
    ],
    Laguna: [
      {
        code: "92-9W-93",
        label: "92-9W-93",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Laguna-SC-92-9W-93.png"),
      },
      {
        code: "e3-90-e4",
        label: "e3-90-e4",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Laguna-SC-e3-90-e4.png"),
      },
      {
        code: "E4-90-E3",
        label: "E4-90-E3",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Laguna-SC-E4-90-E3.png"),
      },
      {
        code: "19-10-9WE2-E4",
        label: "19-10-9WE2-E4",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Laguna-SC-19-10-9WE2-E4.png"),
      },
      {
        code: "E4-90-11-90-E3",
        label: "E4-90-11-90-E3",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Laguna-SC-E4-90-11-90-E3.png"),
      },
    ],
    Henry: [
      {
        code: "47-10-09-10-46",
        label: "47-10-09-10-46",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Henry-SC-47-10-09-10-46.png"),
      },
      {
        code: "67-10-09-10-66",
        label: "67-10-09-10-66",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Henry-SC-67-10-09-10-66.png"),
      },
      {
        code: "67-10-09-6H-66",
        label: "67-10-09-6H-66",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Henry-SC-67-10-09-6H-66.png"),
      },
      {
        code: "67-W2-10-09-10-66",
        label: "67-W2-10-09-10-66",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Henry-SC-67-W2-10-09-10-66.png"),
      },
      {
        code: "67-W2-10-09-6H-66",
        label: "67-W2-10-09-6H-66",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Henry-SC-67-W2-10-09-6H-66.png"),
      },
    ],
    Essex: [
      {
        code: "07-9w-08",
        label: "07-9w-08",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Essex-SC-07-9w-08.png"),
      },
      {
        code: "LB-9W-LA",
        label: "LB-9W-LA",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Essex-SC-LB-9W-LA.png"),
      },
      {
        code: "LD-9W-LA",
        label: "LD-9W-LA",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Essex-SC-LD-9W-LA.png"),
      },
      {
        code: "LH-9W-10-LA",
        label: "LH-9W-10-LA",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Essex-SC-LH-9W-10-LA.png"),
      },
    ],
    Luna: [
      {
        code: "07-9w-08",
        label: "07-9w-08",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Luna-SC-07-9w-08.png"),
      },
      {
        code: "LB-9W-LA",
        label: "LB-9W-LA",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Luna-SC-LB-9W-LA.png"),
      },
      {
        code: "LD-9W-LA",
        label: "LD-9W-LA",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Luna-SC-LD-9W-LA.png"),
      },
      {
        code: "LD-9W-10-LA",
        label: "LD-9W-10-LA",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Luna-SC-LD-9W-10-LA.png"),
      },
    ],
    Harlo: [
      {
        code: "47-10-09-10-46",
        label: "47-10-09-10-46",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Harlo-SC-47-10-09-10-46.png"),
      },
      {
        code: "67-10-09-60-66",
        label: "67-10-09-60-66",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Harlo-SC-67-10-09-60-66.png"),
      },
      {
        code: "88-81-11-81-04",
        label: "88-81-11-81-04",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Harlo-SC-88-81-11-81-04.png"),
      },
      {
        code: "67-A2-10-09-10-66",
        label: "67-A2-10-09-10-66",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Harlo-SC-67-A2-10-09-10-66.png"),
      },
      {
        code: "67-A2-10-09-60-66",
        label: "67-A2-10-09-60-66",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Harlo-SC-67-A2-10-09-60-66.png"),
      },
    ],
    Asher: [
      {
        code: "67-10-9x-10-66",
        label: "67-10-9x-10-66",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Asher-SC-67-10-9x-10-66.png"),
      },
      {
        code: "L2-L3-9X-10-L1",
        label: "L2-L3-9X-10-L1",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Asher-SC-L2-L3-9X-10-L1.png"),
      },
      {
        code: "L2-K2-10-9X-10-L1",
        label: "L2-K2-10-9X-10-L1",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Asher-SC-L2-K2-10-9X-10-L1.png"),
      },
      {
        code: "L2-K2-L3-9X-6H-L1",
        label: "L2-K2-L3-9X-6H-L1",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Asher-SC-L2-K2-L3-9X-6H-L1.png"),
      },
    ],
    Hastings: [
      {
        code: "67-10-9x-10-66",
        label: "67-10-9x-10-66",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Hastings-SC-67-10-9x-10-66.png"),
      },
      {
        code: "L2-L3-9X-10-L1",
        label: "L2-L3-9X-10-L1",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Hastings-SC-L2-L3-9X-10-L1.png"),
      },
      {
        code: "L2-K2-10-9X-10-L1",
        label: "L2-K2-10-9X-10-L1",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Hastings-SC-L2-K2-10-9X-10-L1.png"),
      },
      {
        code: "L2-K2-L3-9X-6H-L1",
        label: "L2-K2-L3-9X-6H-L1",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Hastings-SC-L2-K2-L3-9X-6H-L1.png"),
      },
    ],
    Keiran: [
      {
        code: "67-10-9x-10-66",
        label: "67-10-9x-10-66",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Keiran-SC-67-10-9x-10-66.png"),
      },
      {
        code: "L2-L3-9X-10-L1",
        label: "L2-L3-9X-10-L1",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Keiran-SC-L2-L3-9X-10-L1.png"),
      },
      {
        code: "L2-K2-10-9X-10-L1",
        label: "L2-K2-10-9X-10-L1",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Keiran-SC-L2-K2-10-9X-10-L1.png"),
      },
      {
        code: "L2-K2-L3-9X-6H-L1",
        label: "L2-K2-L3-9X-6H-L1",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Keiran-SC-L2-K2-L3-9X-6H-L1.png"),
      },
    ],
    Kenaston: [
      {
        code: "67-10-9x-10-66",
        label: "67-10-9x-10-66",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Kenaston-SC-67-10-9x-10-66.png"),
      },
      {
        code: "L2-L3-9X-10-L1",
        label: "L2-L3-9X-10-L1",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Kenaston-SC-L2-L3-9X-10-L1.png"),
      },
      {
        code: "L2-K2-10-9X-10-L1",
        label: "L2-K2-10-9X-10-L1",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Kenaston-SC-L2-K2-10-9X-10-L1.png"),
      },
      {
        code: "L2-K2-L3-9X-6H-L1",
        label: "L2-K2-L3-9X-6H-L1",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Kenaston-SC-L2-K2-L3-9X-6H-L1.png"),
      },
    ],
    Leighton: [
      {
        code: "67-10-9x-10-66",
        label: "67-10-9x-10-66",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Leighton-SC-67-10-9x-10-66.png"),
      },
      {
        code: "L2-L3-9X-10-L1",
        label: "L2-L3-9X-10-L1",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Leighton-SC-L2-L3-9X-10-L1.png"),
      },
      {
        code: "L2-K2-10-9X-10-L1",
        label: "L2-K2-10-9X-10-L1",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Leighton-SC-L2-K2-10-9X-10-L1.png"),
      },
      {
        code: "L2-K2-L3-9X-6H-L1",
        label: "L2-K2-L3-9X-6H-L1",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Leighton-SC-L2-K2-L3-9X-6H-L1.png"),
      },
    ],
    Keoni: [
      {
        code: "7p-6h-9a-70-6p",
        label: "7p-6h-9a-70-6p",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Keoni-SC-7p-6h-9a-70-6p.png"),
      },
      {
        code: "C4-70-9A-6H-17",
        label: "C4-70-9A-6H-17",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Keoni-SC-C4-70-9A-6H-17.png"),
      },
      {
        code: "7P-K3-70-9A-70-6P",
        label: "7P-K3-70-9A-70-6P",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Keoni-SC-7P-K3-70-9A-70-6P.png"),
      },
      {
        code: "7P-K3-70-9A-70-C3",
        label: "7P-K3-70-9A-70-C3",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Keoni-SC-7P-K3-70-9A-70-C3.png"),
      },
    ],
    Armina: [
      {
        code: "7p-6h-9a-70-6p",
        label: "7p-6h-9a-70-6p",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Armina-SC-7p-6h-9a-70-6p.png"),
      },
      {
        code: "C4-70-9A-6H-17",
        label: "C4-70-9A-6H-17",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Armina-SC-C4-70-9A-6H-17.png"),
      },
      {
        code: "7P-K3-70-9A-70-6P",
        label: "7P-K3-70-9A-70-6P",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Armina-SC-7P-K3-70-9A-70-6P.png"),
      },
      {
        code: "7P-K3-70-9A-70-C3",
        label: "7P-K3-70-9A-70-C3",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Armina-SC-7P-K3-70-9A-70-C3.png"),
      },
    ],
    Colton: [
      {
        code: "7p-6h-9a-70-6p",
        label: "7p-6h-9a-70-6p",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Colton-SC-7p-6h-9a-70-6p.png"),
      },
      {
        code: "C4-70-9A-6H-17",
        label: "C4-70-9A-6H-17",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Colton-SC-C4-70-9A-6H-17.png"),
      },
      {
        code: "7P-K3-70-9A-70-6P",
        label: "7P-K3-70-9A-70-6P",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Colton-SC-7P-K3-70-9A-70-6P.png"),
      },
      {
        code: "7P-K3-70-9A-70-C3",
        label: "7P-K3-70-9A-70-C3",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Colton-SC-7P-K3-70-9A-70-C3.png"),
      },
    ],
    Apex: [
      {
        code: "5w-1w-1l-s2-4w",
        label: "5w-1w-1l-s2-4w",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Apex-SC-5w-1w-1l-s2-4w.png"),
      },
      {
        code: "5W-S2-1L-S2-C3",
        label: "5W-S2-1L-S2-C3",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Apex-SC-5W-S2-1L-S2-C3.png"),
      },
      {
        code: "5H-F2-1H-19-S1-4H",
        label: "5H-F2-1H-19-S1-4H",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Apex-SC-5H-F2-1H-19-S1-4H.png"),
      },
      {
        code: "5W-F2-S2-19-S2-4W",
        label: "5W-F2-S2-19-S2-4W",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Apex-SC-5W-F2-S2-19-S2-4W.png"),
      },
    ],
    Lotus: [
      {
        code: "5w-1w-1l-s2-4w",
        label: "5w-1w-1l-s2-4w",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Lotus-SC-5w-1w-1l-s2-4w.png"),
      },
      {
        code: "7P-6H-9A-70-6P",
        label: "7P-6H-9A-70-6P",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Lotus-SC-7P-6H-9A-70-6P.png"),
      },
      {
        code: "C4-70-9A-6H-17",
        label: "C4-70-9A-6H-17",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Lotus-SC-C4-70-9A-6H-17.png"),
      },
      {
        code: "7P-K3-70-9A-70-6P",
        label: "7P-K3-70-9A-70-6P",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Lotus-SC-7P-K3-70-9A-70-6P.png"),
      },
      {
        code: "7P-K3-70-9A-70-C3",
        label: "7P-K3-70-9A-70-C3",
        configurationTitle: "",
        description: "",
        priceDiff: 0,
        image: img("Lotus-SC-7P-K3-70-9A-70-C3.png"),
      },
    ],
  };

  window.SECTIONAL_CONFIGS = window.MTL_SECTIONAL_CONFIGS;

  console.log("sectional-configs", "registry-merge-v3-pdp-auth-inline", window.MTL_SECTIONAL_CONFIGS);

  /* MC_SECTIONAL_PDP_STACK_EMERGENCY_20260528d — layout before auth bundle (cached CSS safe) */
  (function (d) {
    if (d.getElementById("mc-pdp-stack-emergency-css")) return;
    var s = d.createElement("style");
    s.id = "mc-pdp-stack-emergency-css";
    s.textContent =
      "body.productdetails #mc-pdp-price-stack-host,body.mc-pdp-price-stack #mc-pdp-price-stack-host{display:flex!important;flex-direction:column!important;gap:6px!important;width:100%!important;margin:0 0 12px!important;position:static!important}" +
      "body.productdetails #mc-pdp-price-stack-host .mc-pdp-retail-row,body.productdetails #mc-pdp-price-stack-host .mc-pdp-member-pricing{display:flex!important;flex-direction:column!important;position:static!important;margin:0 0 4px!important;width:100%!important;visibility:visible!important;opacity:1!important}" +
      "body.productdetails #mtl-product-summary .mtl-summary-row:has(#mtl-sum-price){display:none!important;height:0!important;overflow:hidden!important;opacity:0!important}" +
      "body.productdetails .mc-member-price-caption,body.productdetails #v65-product-parent .colors_pricebox>.mc-pdp-member-line{display:none!important;height:0!important;overflow:hidden!important;opacity:0!important}" +
      "body.productdetails #v65-product-parent .colors_pricebox .mc-pdp-retail-row,body.productdetails #v65-product-parent .colors_pricebox .mc-pdp-member-pricing{display:none!important;height:0!important;overflow:hidden!important;opacity:0!important}";
    (d.head || d.documentElement).appendChild(s);
  })(document);

  /* MC_SECTIONAL_PDP_AUTH_INLINE_20260528 — no external boot.js (404-safe); load auth fix with cache bust */
  (function (g, d) {
    var WANT = "20260523boot";
    function ensure() {
      try {
        var onPdp =
          (d.body && d.body.classList.contains("productdetails")) ||
          !!d.getElementById("v65-product-parent");
        if (!onPdp) return;
        if (String(g.__MC_PDP_AUTH_CTA_FIX_VER__ || "") === WANT) return;
        d.querySelectorAll('script[src*="mc-pdp-auth-cta-fix.js"]').forEach(function (old) {
          try {
            old.remove();
          } catch (eRm) {}
        });
        delete g.__MC_PDP_AUTH_CTA_FIX_VER__;
        var s = d.createElement("script");
        s.id = "mc-pdp-auth-cta-inline-loader";
        s.src = "/v/vspfiles/js/mc-pdp-auth-cta-fix.js?v=" + WANT + "&mcrd=" + Date.now();
        s.async = false;
        (d.head || d.documentElement).appendChild(s);
      } catch (eLoad) {}
    }
    ensure();
    if (d.readyState === "loading") {
      d.addEventListener("DOMContentLoaded", ensure);
    }
    g.addEventListener("load", ensure);
    [0, 200, 600, 1500, 4000].forEach(function (ms) {
      g.setTimeout(ensure, ms);
    });
  })(window, document);
})();
