/**
 * Sectional configuration diagram cards — AUTO-GENERATED by
 *   py -3 tools/sectional-diagrams/build_sectional_configs_from_registry.py
 * Source: tools/sectional-diagrams/sectional_styles_registry.json + Palliser PDFs.
 */
(function () {
  var _base =
    typeof window !== "undefined" && window.MTL_SECTIONAL_DIAGRAM_BASE
      ? String(window.MTL_SECTIONAL_DIAGRAM_BASE).trim()
      : "https://raw.githubusercontent.com/emcc10/mccabe-site/main/vspfiles/sectional-diagrams/";
  if (!_base) {
    _base = "https://raw.githubusercontent.com/emcc10/mccabe-site/main/vspfiles/sectional-diagrams/";
  }
  _base = _base.replace(/\/?$/, '/');

  function img(name) {
    return _base + name;
  }

  window.MTL_SECTIONAL_CONFIGS = {
    Alula: [
      {
        code: "07-15",
        label: "07-15",
        configurationTitle: "4-Seat Bumper Sectional",
        description: "",
        priceDiff: 0,
        image: img("Alula-SC-07-15.png"),
      },
      {
        code: "07-09-19",
        label: "07-09-19",
        configurationTitle: "214 x 158 cm",
        description: "",
        priceDiff: 0,
        image: img("Alula-SC-07-09-19.png"),
      },
      {
        code: "07-09-08",
        label: "07-09-08",
        configurationTitle: "5-Seat L-Sectional",
        description: "",
        priceDiff: 0,
        image: img("Alula-SC-07-09-08.png"),
      },
      {
        code: "12-40",
        label: "12-40",
        configurationTitle: "252 x 252 cm",
        description: "",
        priceDiff: 0,
        image: img("Alula-SC-12-40.png"),
      },
    ],
    Acacia: [
      {
        code: "67-10-09-60-66",
        label: "67-10-09-60-66",
        configurationTitle: "Recliners",
        description: "",
        priceDiff: 0,
        image: img("Acacia-SC-67-10-09-60-66.png"),
      },
      {
        code: "67-10-09-10-66",
        label: "67-10-09-10-66",
        configurationTitle: "299 x 266 cm",
        description: "",
        priceDiff: 0,
        image: img("Acacia-SC-67-10-09-10-66.png"),
      },
    ],
    Atticus: [
      {
        code: "07-15",
        label: "07-15",
        configurationTitle: "4-Seat L-Sectional",
        description: "",
        priceDiff: 0,
        image: img("Atticus-SC-07-15.png"),
      },
      {
        code: "07-40",
        label: "07-40",
        configurationTitle: "239 x 145 cm",
        description: "",
        priceDiff: 0,
        image: img("Atticus-SC-07-40.png"),
      },
      {
        code: "07-11-08",
        label: "07-11-08",
        configurationTitle: "4-Seat L-Sectional",
        description: "",
        priceDiff: 0,
        image: img("Atticus-SC-07-11-08.png"),
      },
    ],
    Colebrook: [
      {
        code: "07-15",
        label: "07-15",
        configurationTitle: "4-Seat L-Sectional",
        description: "",
        priceDiff: 0,
        image: img("Colebrook-SC-07-15.png"),
      },
      {
        code: "07-40",
        label: "07-40",
        configurationTitle: "244 x 174 cm",
        description: "",
        priceDiff: 0,
        image: img("Colebrook-SC-07-40.png"),
      },
      {
        code: "07-35",
        label: "07-35",
        configurationTitle: "5-Seat L-Sectional",
        description: "",
        priceDiff: 0,
        image: img("Colebrook-SC-07-35.png"),
      },
      {
        code: "12-40",
        label: "12-40",
        configurationTitle: "262 x 239 cm",
        description: "",
        priceDiff: 0,
        image: img("Colebrook-SC-12-40.png"),
      },
    ],
    Creighton: [
      {
        code: "12-40",
        label: "12-40",
        configurationTitle: "4-Seat L-Sectional",
        description: "",
        priceDiff: 0,
        image: img("Creighton-SC-12-40.png"),
      },
      {
        code: "07-40",
        label: "07-40",
        configurationTitle: "290 x 227 cm",
        description: "",
        priceDiff: 0,
        image: img("Creighton-SC-07-40.png"),
      },
      {
        code: "07-09-08",
        label: "07-09-08",
        configurationTitle: "5-Seat Chaise Sectional",
        description: "",
        priceDiff: 0,
        image: img("Creighton-SC-07-09-08.png"),
      },
      {
        code: "12-35",
        label: "12-35",
        configurationTitle: "260 x 260 cm",
        description: "",
        priceDiff: 0,
        image: img("Creighton-SC-12-35.png"),
      },
      {
        code: "12-35",
        label: "12-35",
        configurationTitle: "4-Seat Bumper Sectional",
        description: "",
        priceDiff: 0,
        image: img("Creighton-SC-12-35.png"),
      },
    ],
    Lexi: [
      {
        code: "92-15",
        label: "92-15",
        configurationTitle: "4-Seat L-Sectional",
        description: "",
        priceDiff: 0,
        image: img("Lexi-SC-92-15.png"),
      },
      {
        code: "92-40",
        label: "92-40",
        configurationTitle: "262 x 155 cm",
        description: "",
        priceDiff: 0,
        image: img("Lexi-SC-92-40.png"),
      },
      {
        code: "39-10-19",
        label: "39-10-19",
        configurationTitle: "4-Seat Bumper Sectional",
        description: "",
        priceDiff: 0,
        image: img("Lexi-SC-39-10-19.png"),
      },
    ],
    Barrett: [
      {
        code: "07-15",
        label: "07-15",
        configurationTitle: "4-Seat Bumper Sectional",
        description: "",
        priceDiff: 0,
        image: img("Barrett-SC-07-15.png"),
      },
      {
        code: "39-14-15",
        label: "39-14-15",
        configurationTitle: "234 x 150 cm",
        description: "",
        priceDiff: 0,
        image: img("Barrett-SC-39-14-15.png"),
      },
      {
        code: "12-35",
        label: "12-35",
        configurationTitle: "5-Seat Chaise Sectional",
        description: "",
        priceDiff: 0,
        image: img("Barrett-SC-12-35.png"),
      },
    ],
    Corissa: [
      {
        code: "07-09-19",
        label: "07-09-19",
        configurationTitle: "3-Seat Chaise Sectional",
        description: "",
        priceDiff: 0,
        image: img("Corissa-SC-07-09-19.png"),
      },
      {
        code: "07-15",
        label: "07-15",
        configurationTitle: "249 x 260 cm",
        description: "",
        priceDiff: 0,
        image: img("Corissa-SC-07-15.png"),
      },
      {
        code: "07-09-08",
        label: "07-09-08",
        configurationTitle: "5-Seat L-Sectional",
        description: "",
        priceDiff: 0,
        image: img("Corissa-SC-07-09-08.png"),
      },
      {
        code: "12-40",
        label: "12-40",
        configurationTitle: "249 x 249 cm",
        description: "",
        priceDiff: 0,
        image: img("Corissa-SC-12-40.png"),
      },
    ],
    Juno: [
      {
        code: "07-09-19",
        label: "07-09-19",
        configurationTitle: "3-Seat Chaise Sectional",
        description: "",
        priceDiff: 0,
        image: img("Juno-SC-07-09-19.png"),
      },
      {
        code: "07-15",
        label: "07-15",
        configurationTitle: "257 x 254 cm",
        description: "",
        priceDiff: 0,
        image: img("Juno-SC-07-15.png"),
      },
      {
        code: "07-09-08",
        label: "07-09-08",
        configurationTitle: "5-Seat L-Sectional",
        description: "",
        priceDiff: 0,
        image: img("Juno-SC-07-09-08.png"),
      },
      {
        code: "12-40",
        label: "12-40",
        configurationTitle: "257 x 257 cm",
        description: "",
        priceDiff: 0,
        image: img("Juno-SC-12-40.png"),
      },
    ],
    Jura: [
      {
        code: "12-35",
        label: "12-35",
        configurationTitle: "4-Seat Bumper Sectional",
        description: "",
        priceDiff: 0,
        image: img("Jura-SC-12-35.png"),
      },
    ],
    Brookes: [
      {
        code: "92-15",
        label: "92-15",
        configurationTitle: "2-Piece 4-Seat L-Sectional",
        description: "",
        priceDiff: 0,
        image: img("Brookes-SC-92-15.png"),
      },
      {
        code: "92-40",
        label: "92-40",
        configurationTitle: "270 x 155 cm",
        description: "",
        priceDiff: 0,
        image: img("Brookes-SC-92-40.png"),
      },
      {
        code: "39-10-19",
        label: "39-10-19",
        configurationTitle: "3-Piece 4-Seat L-Sectional",
        description: "",
        priceDiff: 0,
        image: img("Brookes-SC-39-10-19.png"),
      },
      {
        code: "92-11-93",
        label: "92-11-93",
        configurationTitle: "262 x 326 cm",
        description: "",
        priceDiff: 0,
        image: img("Brookes-SC-92-11-93.png"),
      },
    ],
    Leeds: [
      {
        code: "07-40",
        label: "07-40",
        configurationTitle: "4-Seat Corner Curve Sectional",
        description: "",
        priceDiff: 0,
        image: img("Leeds-SC-07-40.png"),
      },
      {
        code: "07-09-08",
        label: "07-09-08",
        configurationTitle: "241 x 237 cm",
        description: "",
        priceDiff: 0,
        image: img("Leeds-SC-07-09-08.png"),
      },
      {
        code: "12-35",
        label: "12-35",
        configurationTitle: "5-Seat L-Sectional",
        description: "",
        priceDiff: 0,
        image: img("Leeds-SC-12-35.png"),
      },
      {
        code: "12-40",
        label: "12-40",
        configurationTitle: "299 x 214 cm",
        description: "",
        priceDiff: 0,
        image: img("Leeds-SC-12-40.png"),
      },
    ],
    Charli: [
      {
        code: "E4-90-E3",
        label: "E4-90-E3",
        configurationTitle: "356 x 308 cm",
        description: "",
        priceDiff: 0,
        image: img("Charli-SC-E4-90-E3.png"),
      },
    ],
    Laguna: [
      {
        code: "E4-90-E3",
        label: "E4-90-E3",
        configurationTitle: "394 x 351 cm",
        description: "",
        priceDiff: 0,
        image: img("Laguna-SC-E4-90-E3.png"),
      },
    ],
    Henry: [
      {
        code: "67-10-09-10-66",
        label: "67-10-09-10-66",
        configurationTitle: "304 x 271 cm",
        description: "",
        priceDiff: 0,
        image: img("Henry-SC-67-10-09-10-66.png"),
      },
    ],
    Harlo: [
      {
        code: "67-10-09-60-66",
        label: "67-10-09-60-66",
        configurationTitle: "Recliners",
        description: "",
        priceDiff: 0,
        image: img("Harlo-SC-67-10-09-60-66.png"),
      },
      {
        code: "47-10-09-10-46",
        label: "47-10-09-10-46",
        configurationTitle: "300 x 267 cm",
        description: "",
        priceDiff: 0,
        image: img("Harlo-SC-47-10-09-10-46.png"),
      },
    ],
  };

  window.SECTIONAL_CONFIGS = window.MTL_SECTIONAL_CONFIGS;

  console.log("sectional-configs", "registry-auto", window.MTL_SECTIONAL_CONFIGS);
})();
