#!/usr/bin/env python3
"""
Build vspfiles/js/sectional-configs.js + palliser entries for tools/sectional-diagrams/catalog.json
from sectional_styles_registry.json by scanning each Palliser Product Summary PDF Popular page.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

try:
    import fitz  # PyMuPDF
except ImportError:
    print("pip install pymupdf", file=sys.stderr)
    raise SystemExit(1)

import urllib.request
from urllib.parse import quote

ROOT = Path(__file__).resolve().parent.parent.parent
TOOL = Path(__file__).resolve().parent
REG = TOOL / "sectional_styles_registry.json"
OUT_JS = ROOT / "vspfiles" / "js" / "sectional-configs.js"
OUT_CAT = TOOL / "catalog.json"
PDF_DIR = TOOL / "pdfs"
BASE = "https://images.palliser.com/specsheet/en/"
UA = "McCabeSite-SectionalDiagramExport/1.1"


def fetch_pdf(model: str, token: str) -> bytes:
    url = BASE + quote(f"{model.strip()} {token.strip()}") + ".pdf"
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=120) as r:
        return r.read()


def load_pdf(key: str, model: str, token: str) -> fitz.Document:
    pdf_path = PDF_DIR / f"{key}.pdf"
    if not pdf_path.is_file():
        blob = fetch_pdf(model, token)
        pdf_path.parent.mkdir(parents=True, exist_ok=True)
        pdf_path.write_bytes(blob)
    return fitz.open(pdf_path.as_posix())


def popular_page_lines(doc: fitz.Document) -> list[str]:
    lines: list[str] = []
    for i in range(len(doc)):
        t = doc[i].get_text("text") or ""
        if "POPULAR CONFIGURATIONS" not in t.upper():
            continue
        for ln in t.splitlines():
            s = ln.strip()
            if s:
                lines.append(s)
    return lines


def is_config_code_line(s: str) -> bool:
    s = s.strip()
    if not s or " " in s or len(s) > 56:
        return False
    parts = s.split("/")
    if len(parts) < 2 or len(parts) > 8:
        return False
    for p in parts:
        if not re.fullmatch(r"[0-9A-Za-z]{1,6}", p):
            return False
    if re.fullmatch(r"\d{2,3}/\d{2,3}", s) and len(parts) == 2:
        a, b = int(parts[0]), int(parts[1])
        if 50 <= a <= 220 and 50 <= b <= 220:
            return False
    if len(parts) >= 3 and all(re.fullmatch(r"[A-Za-z0-9]{1,5}", p) for p in parts):
        if not all(p.isdigit() for p in parts):
            return True
    patterns = [
        r"^\d{2}(?:/\d{2})+$",
        r"^\d{2}/\d{2}/\d[A-Za-z]/\d{2}$",
        r"^[A-Za-z]\d/\d{2}/[A-Za-z]\d$",
        r"^\d(?:/[A-Za-z]\d){4,}$",
        r"^[A-Za-z]\d(?:/[A-Za-z]?\d){2,}$",
    ]
    return any(re.match(p, s) for p in patterns)


def prune_subcodes(codes: list[str]) -> list[str]:
    sl = sorted(set(codes), key=lambda x: (-len(x), x))
    keep: list[str] = []
    for c in sl:
        if any(c != k and k.startswith(c + "/") for k in sl):
            continue
        keep.append(c)
    return sorted(keep, key=lambda x: (-len(x), x))


def extract_pairs(lines: list[str]) -> list[tuple[str, str]]:
    raw: list[tuple[str, str, str]] = []  # dash, slash, title
    prev = ""
    for s in lines:
        if is_config_code_line(s):
            slash = s
            dash = s.replace("/", "-")
            title = prev.strip() if prev else "Configuration"
            if title.upper().startswith("POPULAR"):
                title = "Configuration"
            raw.append((dash, slash, title))
        if not is_config_code_line(s):
            prev = s
    slash_list = [b for _, b, __ in raw]
    good_slash = set(prune_subcodes(slash_list))
    return [(a, c) for a, b, c in raw if b in good_slash]


def js_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def build_js(registry: dict) -> str:
    lines_out: list[str] = []
    lines_out.append("/**")
    lines_out.append(" * Sectional configuration diagram cards — AUTO-GENERATED by")
    lines_out.append(" *   py -3 tools/sectional-diagrams/build_sectional_configs_from_registry.py")
    lines_out.append(" * Source: tools/sectional-diagrams/sectional_styles_registry.json + Palliser PDFs.")
    lines_out.append(" */")
    lines_out.append("(function () {")
    lines_out.append(
        '  var _base =\n    typeof window !== "undefined" && window.MTL_SECTIONAL_DIAGRAM_BASE\n'
        '      ? String(window.MTL_SECTIONAL_DIAGRAM_BASE).trim()\n'
        '      : "https://raw.githubusercontent.com/emcc10/mccabe-site/main/vspfiles/sectional-diagrams/";\n'
        "  if (!_base) {\n"
        '    _base = "https://raw.githubusercontent.com/emcc10/mccabe-site/main/vspfiles/sectional-diagrams/";\n'
        "  }\n"
        "  _base = _base.replace(/\\/?$/, '/');\n"
        "\n"
        "  function img(name) {\n"
        "    return _base + name;\n"
        "  }\n"
        "\n"
        "  window.MTL_SECTIONAL_CONFIGS = {"
    )

    for row in registry["styles"]:
        key = row["key"]
        model = row["model"]
        token = row["token"]
        print("SCAN", key, model, token, flush=True)
        doc = load_pdf(key, model, token)
        try:
            plines = popular_page_lines(doc)
            pairs = extract_pairs(plines)
            if not pairs:
                print("  WARN: no codes", key, flush=True)
                continue
        finally:
            doc.close()

        lines_out.append(f"    {key}: [")
        for code, title in pairs:
            fn = f"{key}-SC-{code}.png"
            lines_out.append("      {")
            lines_out.append(f'        code: "{js_escape(code)}",')
            lines_out.append(f'        label: "{js_escape(code)}",')
            lines_out.append(f'        configurationTitle: "{js_escape(title)}",')
            lines_out.append('        description: "",')
            lines_out.append("        priceDiff: 0,")
            lines_out.append(f'        image: img("{js_escape(fn)}"),')
            lines_out.append("      },")
        lines_out.append("    ],")

    lines_out.append("  };")
    lines_out.append("")
    lines_out.append("  window.SECTIONAL_CONFIGS = window.MTL_SECTIONAL_CONFIGS;")
    lines_out.append("")
    lines_out.append('  console.log("sectional-configs", "registry-auto", window.MTL_SECTIONAL_CONFIGS);')
    lines_out.append("})();")
    return "\n".join(lines_out) + "\n"


def merge_catalog(registry: dict) -> None:
    cat = json.loads(OUT_CAT.read_text(encoding="utf-8"))
    pall = cat.get("palliser") or {}
    defaults = {
        "popularColumnSlackPt": 12,
        "popularCropPadPt": 10,
        "popularImageMinAreaPt2": 4200,
    }
    for row in registry["styles"]:
        key = row["key"]
        entry = {
            "model": str(row["model"]),
            "style": row["token"],
            "pdf": f"{key}.pdf",
            **defaults,
        }
        pall[key] = entry
    cat["palliser"] = pall
    OUT_CAT.write_text(json.dumps(cat, indent=2) + "\n", encoding="utf-8")


def main() -> int:
    reg = json.loads(REG.read_text(encoding="utf-8"))
    OUT_JS.write_text(build_js(reg), encoding="utf-8")
    merge_catalog(reg)
    print("Wrote", OUT_JS, "and", OUT_CAT)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
